name: .NET Framework  CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet Packages
      run: nuget restore EscolaApi.sln

    - name: Build Solution
      run: msbuild EscolaApi.sln /p:Configuration=Release
